stages:
  start_localstack:
    cmd: bash scripts/start_localstack.sh
    outs:
      - localstack_running.log  # Track the state of the container to ensure this stage runs only when needed

  unpack:
    cmd: python build/unpack_to_raw.py --input_dir ./data/raw --bucket_name raw --output_file_name combined_raw.csv --localstack
    deps:
      - build/unpack_to_raw.py
      - data/raw/train
      - data/raw/test
      - data/raw/dev
    outs:
      - s3://raw/combined_raw.csv

  preprocess:
    cmd: python src/preprocess_to_staging.py --bucket_raw raw --bucket_staging staging --input_file combined_raw.csv --output_prefix preprocessed --localstack
    deps:
      - src/preprocess_to_staging.py
      - s3://raw/combined_raw.csv
    outs:
      - s3://staging/preprocessed_train.csv
      - s3://staging/preprocessed_dev.csv
      - s3://staging/preprocessed_test.csv

  process:
    cmd: 
      - python src/process_to_curated.py --bucket_staging staging --bucket_curated curated --input_file preprocessed_train.csv --output_file tokenized_train.csv --localstack
      - python src/process_to_curated.py --bucket_staging staging --bucket_curated curated --input_file preprocessed_test.csv --output_file tokenized_test.csv --localstack
      - python src/process_to_curated.py --bucket_staging staging --bucket_curated curated --input_file preprocessed_dev.csv --output_file tokenized_dev.csv --localstack
    deps:
      - src/process_to_curated.py
      - s3://staging/preprocessed_train.csv
      - s3://staging/preprocessed_dev.csv
      - s3://staging/preprocessed_test.csv
    outs:
      - s3://curated/tokenized_train.csv
      - s3://curated/tokenized_test.csv
      - s3://curated/tokenized_dev.csv
